[bssg]

[build]
step = "steplist"
steps = ["clean", "base", "blog"]

[base]
step = "steplist"
steps = ["mkdocsdir", "cname", "css", "rss", "index"]

[blog]
step = "steplist"
steps = ["mkblogdir", "blogbssg"]

[clean]
step = "rm"
path = "docs"

[mkdocsdir]
step = "mkdir"
path = "docs"

[cname]
step = "cp"
inputFile = "CNAME"
outputFile = "docs/CNAME"

[css]
step = "transformless"
inputFile = "style.less"
outputFile = "docs/style.css"

[rss]
step = "transformpug"
inputFile = "pug/rss.pug"
outputFile = "docs/rss.xml"
localsFile = "data.json"

[index]
step = "transformpug"
inputFile = "pug/index.pug"
outputFile = "docs/index.html"
localsFile = "data.json"

[mkblogdir]
step = "mkdir"
path = "docs/blog"

[blogbssg]
step = "transformmarkdown"
inputFile = "blog/bssg.md"
outputFile = "docs/blog/bssg.html"
extends = "pug/blog.pug"
